// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Ssal.Api.Data;

#nullable disable

namespace Ssal.Api.Migrations
{
    [DbContext(typeof(SsalDbContext))]
    [Migration("20260629123203_ConsultasPresupuestosItems")]
    partial class ConsultasPresupuestosItems
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Ssal.Api.Models.Analisis", b =>
                {
                    b.Property<int>("IdAnalisis")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_analisis");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdAnalisis"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<string>("Area")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("area");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("codigo");

                    b.Property<int>("IdGrupo")
                        .HasColumnType("integer")
                        .HasColumnName("id_grupo");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nombre");

                    b.Property<decimal>("PrecioUsd")
                        .HasColumnType("numeric")
                        .HasColumnName("precio_usd");

                    b.HasKey("IdAnalisis");

                    b.HasIndex("IdGrupo");

                    b.ToTable("analisis");
                });

            modelBuilder.Entity("Ssal.Api.Models.AuditoriaRotulo", b =>
                {
                    b.Property<int>("IdAuditoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_auditoria");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdAuditoria"));

                    b.Property<DateTime>("FechaCambio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_cambio");

                    b.Property<int>("IdRotulo")
                        .HasColumnType("integer")
                        .HasColumnName("id_rotulo");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("integer")
                        .HasColumnName("id_usuario");

                    b.Property<string>("Motivo")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("motivo");

                    b.Property<string>("ValorAnterior")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("valor_anterior");

                    b.Property<string>("ValorNuevo")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("valor_nuevo");

                    b.HasKey("IdAuditoria");

                    b.HasIndex("IdRotulo");

                    b.HasIndex("IdUsuario");

                    b.ToTable("auditorias_rotulo");
                });

            modelBuilder.Entity("Ssal.Api.Models.Cliente", b =>
                {
                    b.Property<int>("IdCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_cliente");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCliente"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("apellido");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("email");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado");

                    b.Property<int?>("IdEmpresa")
                        .HasColumnType("integer")
                        .HasColumnName("id_empresa");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<string>("Telefono")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("telefono");

                    b.Property<string>("UsuarioWeb")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("usuario_web");

                    b.HasKey("IdCliente");

                    b.HasIndex("IdEmpresa");

                    b.ToTable("clientes");
                });

            modelBuilder.Entity("Ssal.Api.Models.Consulta", b =>
                {
                    b.Property<int>("IdConsulta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_consulta");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdConsulta"));

                    b.Property<string>("Canal")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("canal");

                    b.Property<string>("Codigo")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("codigo");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("estado");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha");

                    b.Property<int?>("IdCliente")
                        .HasColumnType("integer")
                        .HasColumnName("id_cliente");

                    b.Property<int?>("IdEmpresa")
                        .HasColumnType("integer")
                        .HasColumnName("id_empresa");

                    b.Property<int?>("IdResponsable")
                        .HasColumnType("integer")
                        .HasColumnName("id_responsable");

                    b.HasKey("IdConsulta");

                    b.HasIndex("IdCliente");

                    b.HasIndex("IdEmpresa");

                    b.HasIndex("IdResponsable");

                    b.ToTable("consultas");
                });

            modelBuilder.Entity("Ssal.Api.Models.Empresa", b =>
                {
                    b.Property<int>("IdEmpresa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_empresa");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdEmpresa"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Cuit")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("cuit");

                    b.Property<string>("Direccion")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("direccion");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("email");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("razon_social");

                    b.Property<string>("Telefono")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("telefono");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("IdEmpresa");

                    b.ToTable("empresas");
                });

            modelBuilder.Entity("Ssal.Api.Models.Factura", b =>
                {
                    b.Property<int>("IdFactura")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_factura");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdFactura"));

                    b.Property<int>("CreadoPor")
                        .HasColumnType("integer")
                        .HasColumnName("creado_por");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha");

                    b.Property<int>("IdSse")
                        .HasColumnType("integer")
                        .HasColumnName("id_sse");

                    b.Property<decimal>("ImporteDolares")
                        .HasColumnType("numeric")
                        .HasColumnName("importe_dolares");

                    b.Property<decimal>("ImportePesos")
                        .HasColumnType("numeric")
                        .HasColumnName("importe_pesos");

                    b.Property<string>("Numero")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("numero");

                    b.HasKey("IdFactura");

                    b.HasIndex("CreadoPor");

                    b.HasIndex("IdSse")
                        .IsUnique();

                    b.ToTable("facturas");
                });

            modelBuilder.Entity("Ssal.Api.Models.FirmaDocumento", b =>
                {
                    b.Property<int>("IdFirma")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_firma");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdFirma"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaFirma")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_firma");

                    b.Property<int>("IdDocumento")
                        .HasColumnType("integer")
                        .HasColumnName("id_documento");

                    b.Property<int>("IdFirmante")
                        .HasColumnType("integer")
                        .HasColumnName("id_firmante");

                    b.Property<string>("MotivoRechazo")
                        .HasColumnType("text")
                        .HasColumnName("motivo_rechazo");

                    b.Property<string>("TipoDocumento")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("tipo_documento");

                    b.Property<string>("TipoFirma")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tipo_firma");

                    b.HasKey("IdFirma");

                    b.HasIndex("IdFirmante");

                    b.ToTable("firmas_documento");
                });

            modelBuilder.Entity("Ssal.Api.Models.GrupoAnalisis", b =>
                {
                    b.Property<int>("IdGrupo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_grupo");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdGrupo"));

                    b.Property<string>("Area")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("area");

                    b.Property<string>("CodigoAgrupador")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("codigo_agrupador");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("descripcion");

                    b.HasKey("IdGrupo");

                    b.ToTable("grupos_analisis");
                });

            modelBuilder.Entity("Ssal.Api.Models.Muestra", b =>
                {
                    b.Property<int>("IdMuestra")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_muestra");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdMuestra"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaRecepcion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_recepcion");

                    b.Property<int>("IdRotulo")
                        .HasColumnType("integer")
                        .HasColumnName("id_rotulo");

                    b.Property<string>("Observacion")
                        .HasColumnType("text")
                        .HasColumnName("observacion");

                    b.Property<int>("RecibidoPor")
                        .HasColumnType("integer")
                        .HasColumnName("recibido_por");

                    b.Property<string>("Tipo")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tipo");

                    b.HasKey("IdMuestra");

                    b.HasIndex("IdRotulo")
                        .IsUnique();

                    b.HasIndex("RecibidoPor");

                    b.ToTable("muestras");
                });

            modelBuilder.Entity("Ssal.Api.Models.Presupuesto", b =>
                {
                    b.Property<int>("IdPresupuesto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_presupuesto");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdPresupuesto"));

                    b.Property<decimal>("AdicionalAsesoramiento")
                        .HasColumnType("numeric")
                        .HasColumnName("adicional_asesoramiento");

                    b.Property<string>("CodigoRpo")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("codigo_rpo");

                    b.Property<decimal>("Cotizacion")
                        .HasColumnType("numeric")
                        .HasColumnName("cotizacion");

                    b.Property<int>("CreadoPor")
                        .HasColumnType("integer")
                        .HasColumnName("creado_por");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("estado");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha");

                    b.Property<int>("IdConsulta")
                        .HasColumnType("integer")
                        .HasColumnName("id_consulta");

                    b.Property<decimal>("ImporteDolares")
                        .HasColumnType("numeric")
                        .HasColumnName("importe_dolares");

                    b.Property<decimal>("ImportePesos")
                        .HasColumnType("numeric")
                        .HasColumnName("importe_pesos");

                    b.HasKey("IdPresupuesto");

                    b.HasIndex("CreadoPor");

                    b.HasIndex("IdConsulta")
                        .IsUnique();

                    b.ToTable("presupuestos");
                });

            modelBuilder.Entity("Ssal.Api.Models.PresupuestoAnalisis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("IdAnalisis")
                        .HasColumnType("integer")
                        .HasColumnName("id_analisis");

                    b.Property<int>("IdPresupuesto")
                        .HasColumnType("integer")
                        .HasColumnName("id_presupuesto");

                    b.Property<decimal>("PrecioUsdSnapshot")
                        .HasColumnType("numeric")
                        .HasColumnName("precio_usd_snapshot");

                    b.HasKey("Id");

                    b.HasIndex("IdAnalisis");

                    b.HasIndex("IdPresupuesto");

                    b.ToTable("presupuesto_analisis");
                });

            modelBuilder.Entity("Ssal.Api.Models.Resultado", b =>
                {
                    b.Property<int>("IdResultado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_resultado");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdResultado"));

                    b.Property<int>("CargadoPor")
                        .HasColumnType("integer")
                        .HasColumnName("cargado_por");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaCarga")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_carga");

                    b.Property<int>("IdAnalisis")
                        .HasColumnType("integer")
                        .HasColumnName("id_analisis");

                    b.Property<int>("IdMuestra")
                        .HasColumnType("integer")
                        .HasColumnName("id_muestra");

                    b.Property<string>("Valor")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("valor");

                    b.HasKey("IdResultado");

                    b.HasIndex("CargadoPor");

                    b.HasIndex("IdAnalisis");

                    b.HasIndex("IdMuestra");

                    b.ToTable("resultados");
                });

            modelBuilder.Entity("Ssal.Api.Models.Rol", b =>
                {
                    b.Property<int>("IdRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_rol");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdRol"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("codigo");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.HasKey("IdRol");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("roles");

                    b.HasData(
                        new
                        {
                            IdRol = 1,
                            Codigo = "ROL-01",
                            Descripcion = "Acceso total. Aprobación final con firma digital.",
                            Nombre = "Administrador general / Director Técnico"
                        },
                        new
                        {
                            IdRol = 2,
                            Codigo = "ROL-02",
                            Descripcion = "Registro de consultas, clientes, SSE y rótulos.",
                            Nombre = "Administrativo"
                        },
                        new
                        {
                            IdRol = 3,
                            Codigo = "ROL-03",
                            Descripcion = "Generación y envío de presupuestos.",
                            Nombre = "Presupuestos"
                        },
                        new
                        {
                            IdRol = 4,
                            Codigo = "ROL-04",
                            Descripcion = "Facturación y seguimiento de deudas.",
                            Nombre = "Cobranzas"
                        },
                        new
                        {
                            IdRol = 5,
                            Codigo = "ROL-05",
                            Descripcion = "Solo lectura en portal web.",
                            Nombre = "Cliente externo"
                        },
                        new
                        {
                            IdRol = 6,
                            Codigo = "ROL-06",
                            Descripcion = "Backoffice técnico. Exclusivo del equipo de desarrollo.",
                            Nombre = "Administrador de sistema"
                        },
                        new
                        {
                            IdRol = 7,
                            Codigo = "ROL-07",
                            Descripcion = "Realiza análisis y carga resultados.",
                            Nombre = "Analista"
                        },
                        new
                        {
                            IdRol = 8,
                            Codigo = "ROL-08",
                            Descripcion = "Supervisa Microbiología. Firma digital de documentos.",
                            Nombre = "Responsable de área MIC"
                        },
                        new
                        {
                            IdRol = 9,
                            Codigo = "ROL-09",
                            Descripcion = "Supervisa Físico Química. Firma digital de documentos.",
                            Nombre = "Responsable de área FQ"
                        });
                });

            modelBuilder.Entity("Ssal.Api.Models.RotuloInterno", b =>
                {
                    b.Property<int>("IdRotulo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_rotulo");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdRotulo"));

                    b.Property<int>("AsignadoPor")
                        .HasColumnType("integer")
                        .HasColumnName("asignado_por");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaAsignacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_asignacion");

                    b.Property<int>("IdSse")
                        .HasColumnType("integer")
                        .HasColumnName("id_sse");

                    b.Property<string>("NumeroUnico")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("numero_unico");

                    b.HasKey("IdRotulo");

                    b.HasIndex("AsignadoPor");

                    b.HasIndex("IdSse")
                        .IsUnique();

                    b.HasIndex("NumeroUnico")
                        .IsUnique();

                    b.ToTable("rotulos_internos");
                });

            modelBuilder.Entity("Ssal.Api.Models.Sse", b =>
                {
                    b.Property<int>("IdSse")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_sse");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdSse"));

                    b.Property<string>("Area")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("area");

                    b.Property<string>("CodigoRpo")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("codigo_rpo");

                    b.Property<int>("CreadoPor")
                        .HasColumnType("integer")
                        .HasColumnName("creado_por");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("estado");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha");

                    b.Property<string>("FormaPago")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("forma_pago");

                    b.Property<int>("IdCliente")
                        .HasColumnType("integer")
                        .HasColumnName("id_cliente");

                    b.Property<int>("IdPresupuesto")
                        .HasColumnType("integer")
                        .HasColumnName("id_presupuesto");

                    b.Property<decimal>("ImporteDolares")
                        .HasColumnType("numeric")
                        .HasColumnName("importe_dolares");

                    b.Property<decimal>("ImportePesos")
                        .HasColumnType("numeric")
                        .HasColumnName("importe_pesos");

                    b.HasKey("IdSse");

                    b.HasIndex("CreadoPor");

                    b.HasIndex("IdCliente");

                    b.HasIndex("IdPresupuesto")
                        .IsUnique();

                    b.ToTable("sses");
                });

            modelBuilder.Entity("Ssal.Api.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_usuario");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdUsuario"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("apellido");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("email");

                    b.Property<bool>("ForzarCambioPwd")
                        .HasColumnType("boolean")
                        .HasColumnName("forzar_cambio_pwd");

                    b.Property<int>("IdRol")
                        .HasColumnType("integer")
                        .HasColumnName("id_rol");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<DateTime?>("UltimoAcceso")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ultimo_acceso");

                    b.HasKey("IdUsuario");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("IdRol");

                    b.ToTable("usuarios");
                });

            modelBuilder.Entity("Ssal.Api.Models.Analisis", b =>
                {
                    b.HasOne("Ssal.Api.Models.GrupoAnalisis", "Grupo")
                        .WithMany("Analisis")
                        .HasForeignKey("IdGrupo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Grupo");
                });

            modelBuilder.Entity("Ssal.Api.Models.AuditoriaRotulo", b =>
                {
                    b.HasOne("Ssal.Api.Models.RotuloInterno", "RotuloInterno")
                        .WithMany("Auditorias")
                        .HasForeignKey("IdRotulo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ssal.Api.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RotuloInterno");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Ssal.Api.Models.Cliente", b =>
                {
                    b.HasOne("Ssal.Api.Models.Empresa", "Empresa")
                        .WithMany("Clientes")
                        .HasForeignKey("IdEmpresa");

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("Ssal.Api.Models.Consulta", b =>
                {
                    b.HasOne("Ssal.Api.Models.Cliente", "Cliente")
                        .WithMany("Consultas")
                        .HasForeignKey("IdCliente");

                    b.HasOne("Ssal.Api.Models.Empresa", "Empresa")
                        .WithMany("Consultas")
                        .HasForeignKey("IdEmpresa");

                    b.HasOne("Ssal.Api.Models.Usuario", "Responsable")
                        .WithMany()
                        .HasForeignKey("IdResponsable")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Cliente");

                    b.Navigation("Empresa");

                    b.Navigation("Responsable");
                });

            modelBuilder.Entity("Ssal.Api.Models.Factura", b =>
                {
                    b.HasOne("Ssal.Api.Models.Usuario", "CreadoPorUsuario")
                        .WithMany()
                        .HasForeignKey("CreadoPor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ssal.Api.Models.Sse", "Sse")
                        .WithOne("Factura")
                        .HasForeignKey("Ssal.Api.Models.Factura", "IdSse")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreadoPorUsuario");

                    b.Navigation("Sse");
                });

            modelBuilder.Entity("Ssal.Api.Models.FirmaDocumento", b =>
                {
                    b.HasOne("Ssal.Api.Models.Usuario", "Firmante")
                        .WithMany()
                        .HasForeignKey("IdFirmante")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Firmante");
                });

            modelBuilder.Entity("Ssal.Api.Models.Muestra", b =>
                {
                    b.HasOne("Ssal.Api.Models.RotuloInterno", "RotuloInterno")
                        .WithOne("Muestra")
                        .HasForeignKey("Ssal.Api.Models.Muestra", "IdRotulo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ssal.Api.Models.Usuario", "RecibidoPorUsuario")
                        .WithMany()
                        .HasForeignKey("RecibidoPor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RecibidoPorUsuario");

                    b.Navigation("RotuloInterno");
                });

            modelBuilder.Entity("Ssal.Api.Models.Presupuesto", b =>
                {
                    b.HasOne("Ssal.Api.Models.Usuario", "CreadoPorUsuario")
                        .WithMany()
                        .HasForeignKey("CreadoPor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ssal.Api.Models.Consulta", "Consulta")
                        .WithOne("Presupuesto")
                        .HasForeignKey("Ssal.Api.Models.Presupuesto", "IdConsulta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Consulta");

                    b.Navigation("CreadoPorUsuario");
                });

            modelBuilder.Entity("Ssal.Api.Models.PresupuestoAnalisis", b =>
                {
                    b.HasOne("Ssal.Api.Models.Analisis", "Analisis")
                        .WithMany()
                        .HasForeignKey("IdAnalisis")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ssal.Api.Models.Presupuesto", "Presupuesto")
                        .WithMany("Items")
                        .HasForeignKey("IdPresupuesto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Analisis");

                    b.Navigation("Presupuesto");
                });

            modelBuilder.Entity("Ssal.Api.Models.Resultado", b =>
                {
                    b.HasOne("Ssal.Api.Models.Usuario", "CargadoPorUsuario")
                        .WithMany()
                        .HasForeignKey("CargadoPor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ssal.Api.Models.Analisis", "Analisis")
                        .WithMany("Resultados")
                        .HasForeignKey("IdAnalisis")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ssal.Api.Models.Muestra", "Muestra")
                        .WithMany("Resultados")
                        .HasForeignKey("IdMuestra")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Analisis");

                    b.Navigation("CargadoPorUsuario");

                    b.Navigation("Muestra");
                });

            modelBuilder.Entity("Ssal.Api.Models.RotuloInterno", b =>
                {
                    b.HasOne("Ssal.Api.Models.Usuario", "AsignadoPorUsuario")
                        .WithMany()
                        .HasForeignKey("AsignadoPor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ssal.Api.Models.Sse", "Sse")
                        .WithOne("RotuloInterno")
                        .HasForeignKey("Ssal.Api.Models.RotuloInterno", "IdSse")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AsignadoPorUsuario");

                    b.Navigation("Sse");
                });

            modelBuilder.Entity("Ssal.Api.Models.Sse", b =>
                {
                    b.HasOne("Ssal.Api.Models.Usuario", "CreadoPorUsuario")
                        .WithMany()
                        .HasForeignKey("CreadoPor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ssal.Api.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ssal.Api.Models.Presupuesto", "Presupuesto")
                        .WithOne("Sse")
                        .HasForeignKey("Ssal.Api.Models.Sse", "IdPresupuesto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("CreadoPorUsuario");

                    b.Navigation("Presupuesto");
                });

            modelBuilder.Entity("Ssal.Api.Models.Usuario", b =>
                {
                    b.HasOne("Ssal.Api.Models.Rol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdRol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("Ssal.Api.Models.Analisis", b =>
                {
                    b.Navigation("Resultados");
                });

            modelBuilder.Entity("Ssal.Api.Models.Cliente", b =>
                {
                    b.Navigation("Consultas");
                });

            modelBuilder.Entity("Ssal.Api.Models.Consulta", b =>
                {
                    b.Navigation("Presupuesto");
                });

            modelBuilder.Entity("Ssal.Api.Models.Empresa", b =>
                {
                    b.Navigation("Clientes");

                    b.Navigation("Consultas");
                });

            modelBuilder.Entity("Ssal.Api.Models.GrupoAnalisis", b =>
                {
                    b.Navigation("Analisis");
                });

            modelBuilder.Entity("Ssal.Api.Models.Muestra", b =>
                {
                    b.Navigation("Resultados");
                });

            modelBuilder.Entity("Ssal.Api.Models.Presupuesto", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("Sse");
                });

            modelBuilder.Entity("Ssal.Api.Models.Rol", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("Ssal.Api.Models.RotuloInterno", b =>
                {
                    b.Navigation("Auditorias");

                    b.Navigation("Muestra");
                });

            modelBuilder.Entity("Ssal.Api.Models.Sse", b =>
                {
                    b.Navigation("Factura");

                    b.Navigation("RotuloInterno");
                });
#pragma warning restore 612, 618
        }
    }
}
